### ISSUE TITLE
pickle dataset mentioned in the 'catalog.yml' file is not present in the data folder after cloning 

### ISSUE THREAD

**Issue by ShankarChavan** [Galileo-Galilei/kedro-mlflow-tutorial#18]
Hi,
Thank you creating the kedro-mlflow integration tool. I was trying to run this tutorial to understand the use of kedro-mlflow, as per the instructions after cloning if we try to run `kedro run --pipeline=etl_instances`  it fails as there is no PickleDataset file present in the `data/01_raw` folder.

Can you please update the branch with pickle files or share the location of the pickle files.

**Comment by shankar-taladra** [comment]
Issue is resolved, the problem was at my end as I was trying to run kedro pipeline behind corporate firewall and it had restricted access to download the imdb dataset from outside.
