### ISSUE TITLE
Update the kedro, kedro-mlflow versions

### ISSUE THREAD

**Issue by Mercurrent** [Galileo-Galilei/kedro-mlflow-tutorial#9]
Hi Galileo-Galilei,

I see this tutorial is based on rather stale versions of kedro-mlflow (0.4.0) and kedro (0.16.6);
Can I suggest any help on updating those? Or you're aware of some upcoming major updates.

**Comment by Galileo-Galilei** [comment]
Hi @Mercurrent, 

You are right and this is in my backlog but I have few time to do this and I focus on the core library for now. 

I'd be more than happy to get some help to update to more recent kedro and kedro-mlflow versions if you want to do it. Actually it should be very straightforward to upgrade to ``kedro==0.17.6`` and ``kedro-mlflow==0.8.1``. We can just generate a project with the new kedro template, and copy paste conf/ and pipelines/ to where they belong and it should "just work". Some slight modifications of the wording in the README may be required (e.g. changing ``ProjectContext`` to ``KedroSession`` in a few places, and other minor changes to match new kedro components).

**Comment by Galileo-Galilei** [comment]
The migration is done for ``kedro==0.17.7``. ``kedro>=0.18`` will follow soon.
